//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.9

use super::prelude::*;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, DeriveIntoActiveModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,

    pub full_name: String,

    #[sea_orm(unique)]
    pub email: String,

    pub password: String,

    #[sea_orm(default_expr = "Now()")]
    pub created_at: ChronoDateTimeUtc,

    #[sea_orm(default_expr = "Now()")]
    pub updated_at: ChronoDateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "Wallets")]
    Wallets,

    #[sea_orm(has_many = "Orders")]
    Orders,

    #[sea_orm(has_many = "Transactions")]
    Transactions,

    // a user can make many trades
    #[sea_orm(
        has_many = "Trades",
        from = "Column::Id",
        to = "super::trades::Column::MakerUserId"
    )]
    Madetrades,

    // a user can be a taker in many trades
    #[sea_orm(
        has_many = "Trades",
        from = "Column::Id",
        to = "super::trades::Column::TakerUserId"
    )]
    Tooktades,
}

impl Related<Wallets> for Entity {
    fn to() -> RelationDef {
        Relation::Wallets.def()
    }
}

impl Related<Orders> for Entity {
    fn to() -> RelationDef {
        Relation::Orders.def()
    }
}

impl Related<Transactions> for Entity {
    fn to() -> RelationDef {
        Relation::Transactions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
